name = "ai-news-signup"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ai-news-subscribers"
database_id = "ce3da545-df65-47b7-aa27-c2f740edc1e9"

[vars]
WORKER_URL = "https://ai-news-signup.julienh15.workers.dev"
SENDER_EMAIL = "julien.hovan@compassdata.ca"

[[kv_namespaces]]
binding = "ARCHIVE_KV"
id = "7aec2dc231d74cc5b0a524b3e22de3d9"

[[r2_buckets]]
binding = "ARCHIVE_R2"
bucket_name = "ai-news-archive"
